### ISSUE TITLE
Feature: Display Not Found Items

### ISSUE THREAD

**Issue by amcnea** [MatthewOverall/tloz-tracker#4]
Show the items not found in an area under the Dungeon/Overworld items.

Segment them so they are broken up by items allowable and not allowable in 9.

Remove item's from the Not Found list as they are added to the Dungeon Overworld Items.

Skip over found items in the group when adding new items to the Dungeon/Overworld items.

**Comment by MatthewOverall** [comment]
Would like to do the same thing for Levels, as they are found, remove them, or fade them in the list.
I like the idea of no duplicate items being able to be marked. 

Maybe add an indicator that shows the probability of a specific item being in lvl 9.

**Comment by MatthewOverall** [comment]
I've added an indicator via triforce color to show which levels have been found. Still need to come up with a solution for items not found.

**Comment by amcnea** [comment]
I've added the functionality to skip over found items in dungeon item cycling.
